# Pandas

## Estrutura de Dados

In [14]:
from pandas import Series, DataFrame
import pandas as pd

#Series associa os index dos valores
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
print(obj.values)
print(obj.index) #obj.index.values

In [15]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
import numpy as np
print(obj2[(obj2 > 0) & (obj2 < 5)])
print(obj2 * 2)
print(np.exp(obj2))

d    4
c    3
dtype: int64
d     8
b    14
a   -10
c     6
dtype: int64
d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64


In [17]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states = ['Oregon', 'Texas','California', 'Ohio']
obj4 = Series(sdata, index=states)
obj4

Oregon        16000.0
Texas         71000.0
California        NaN
Ohio          35000.0
dtype: float64

In [20]:
print(pd.isnull(obj4)) # == obj4.isnull()
print(pd.notnull(obj4))

Oregon        False
Texas         False
California     True
Ohio          False
dtype: bool
Oregon         True
Texas          True
California    False
Ohio           True
dtype: bool


In [ ]:
print(obj3)
print(obj4)
obj3 + obj4

In [ ]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = DataFrame(data)
df

In [ ]:
df2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                index=['one', 'two', 'three', 'four', 'five'])
df2

In [ ]:
print(df['state'])
print(df.year)#não usar, pode ser que tenha um atributo com o mesmo nome da coluna

In [ ]:
print(df2.loc['four']) #label
print(df.iloc[0]) #int

df2[0:2]
df2[['year']]

In [ ]:
#df2['debt'] = np.arange(len(df))
df2['debt'] = np.arange(5)

In [ ]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
df2['debt'] = val
df2

In [ ]:
#Criando coluna com valores lógicos
df2['eastern'] = df2.state == 'Ohio'
df2

In [ ]:
del df2['eastern']
df2

In [ ]:
#retorna uma matriz com os valores das linhas
df.values

In [ ]:
obj = Series(range(3), index=['a', 'b', 'c'])
obj.index.values

In [ ]:
#pertencimento
print('state' in df2.columns)
print(0 in df.index)

## Aplicação de Função e Mapeamento

In [ ]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [1]:
list('bde')

['b', 'd', 'e']

In [ ]:
df = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
np.abs(df) #retorna valor absoluto

In [ ]:
f = lambda x: x.max() - x.min()
print(df.apply(f))#colunas
print(df.apply(f, axis=1))#linhas

In [ ]:
def f2(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

df.apply(f2)

In [ ]:
format2 = lambda x: '%.2f' % x
df.applymap(format2)

## Ordenação e Ranking

In [ ]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
df2 = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
print(obj)
print(df2)
print(obj.sort_index())
print(df2.sort_index())
print(df2.sort_index(axis=1))

In [ ]:
obj = Series([4, 7, -3, 2])
obj.sort_values() #igual para pandas

In [ ]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'nota': [8, 7, 7.5, 10, 5]}
df4 = DataFrame(data)
print(df4)
df4['rank'] = df4['nota'].rank(ascending=0)
df4.sort_values('rank')

## Sumarização e Estatística Descritiva

In [ ]:
df5 = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
print(df5)
print(df5.sum())
print(df5.sum(axis=1))
print(df5.count())

In [ ]:
df5.describe()

In [ ]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

In [ ]:
mask = obj.isin(['b', 'c'])
mask

## Manipulação de Valores Faltantes 

In [ ]:
string_data = Series(['laranja', 'uva', np.nan, 'abacate'])
print(string_data)
print(string_data.isnull())
string_data[0] = None
print(string_data.isnull())

In [ ]:
data = DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                  [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
print(data)
cleaned = data.dropna()
print('\n',cleaned)
data.dropna(how='all')

In [ ]:
print(data.fillna(0))
print(data.fillna(data.mean()))

## TODO Section

### Manipulação de DataFrame

        > Crie, a partir do dicionário abaixo, um DataFrame cujo index seja os valores da variável labels
        > encontre a média dos valores da coluna age e preencha os valores faltantes dessa coluna com o valor da média
        > crie uma nova coluna chamada 'rank', que mostre os animais que receberam mais visitas
        > qual o animal que recebeu a maior quantidade de visitas?

In [3]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [27]:
# TODO: sua resposta aqui
from pandas import Series, DataFrame

#A
df1 = DataFrame(data, index=labels)

#B
df1['age'] = df1['age'].fillna(df1['age'].mean())

#C
df1['rank'] = df1['visits'].rank()

#D
df1 = df1.sort_values(by='rank', ascending=False)

df1[df1['visits']==df1['visits'].max()]



animal     age  visits priority  rank
b    cat  3.0000       3      yes   9.0
d    dog  3.4375       3      yes   9.0
f    cat  2.0000       3       no   9.0

## Carregamento e Armazenamento de Dados

### Arquivo CSV

In [29]:
import pandas as pd
poke = pd.read_csv('bases/Pokemon.csv')
poke.head(n=10)#10 primeiras linhas

#                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1                  Bulbasaur  Grass  Poison    318  45      49       49   
1  2                    Ivysaur  Grass  Poison    405  60      62       63   
2  3                   Venusaur  Grass  Poison    525  80      82       83   
3  3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4                 Charmander   Fire     NaN    309  39      52       43   
5  5                 Charmeleon   Fire     NaN    405  58      64       58   
6  6                  Charizard   Fire  Flying    534  78      84       78   
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111   
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78   
9  7                   Squirtle  Water     NaN    314  44      48       65   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False  
5       80       65     80           1      False  
6      109       85    100           1      False  
7      130       85    100           1      False  
8      159      115    100           1      False  
9       50       64     43           1      False

### Arquivo JSON

In [30]:
obj = """
{"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"},
{"name": "Katie", "age": 33, "pet": "Cisco"}]
}
"""
print(type(obj))
print(obj)

<class 'str'>

{"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"},
{"name": "Katie", "age": 33, "pet": "Cisco"}]
}



In [33]:
import json
result = json.loads(obj)
print(result)
type(result)

{'name': 'Wes', 'places_lived': ['United States', 'Spain', 'Germany'], 'pet': None, 'siblings': [{'name': 'Scott', 'age': 25, 'pet': 'Zuko'}, {'name': 'Katie', 'age': 33, 'pet': 'Cisco'}]}


dict

In [34]:
asjson = json.dumps(result)
print(type(asjson))
asjson

<class 'str'>


'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"}, {"name": "Katie", "age": 33, "pet": "Cisco"}]}'

In [35]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

name  age
0  Scott   25
1  Katie   33

### SQL

In [37]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER
);"""

In [39]:
con = sqlite3.connect(':memory:')#Cria conexão em memory
con.execute(query)
con.commit()

In [40]:
data = [('Atlanta', 'Georgia', 1.25, 6),
('Tallahassee', 'Florida', 2.6, 3),
('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [41]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [42]:
print(cursor.description)
#* faz uma descompactação do primeiro valor
pd.DataFrame(rows, columns=list(zip(*cursor.description))[0])

(('a', None, None, None, None, None, None), ('b', None, None, None, None, None, None), ('c', None, None, None, None, None, None), ('d', None, None, None, None, None, None))


a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [43]:
#Maneira pythonica
import pandas.io.sql as sql
sql.read_sql_query('select * from test', con)

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

## Combinação de Dados

In [1]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})

df2 = pd.DataFrame({'key': ['a', 'b', 'd','b'],
                 'data2': range(4)})

#pd.merge(df1,df2,on='key') #default inner
pd.merge(df1,df2) #default inner

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      6      1
5   b      6      3
6   a      2      0
7   a      4      0
8   a      5      0

In [4]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})

df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                 'data2': range(3)})
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [6]:
pd.merge(df3, df4, how='outer',left_on='lkey',right_on='rkey')#outer join

lkey  data1 rkey  data2
0    b    0.0    b    1.0
1    b    1.0    b    1.0
2    b    6.0    b    1.0
3    a    2.0    a    0.0
4    a    4.0    a    0.0
5    a    5.0    a    0.0
6    c    3.0  NaN    NaN
7  NaN    NaN    d    2.0

In [7]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                  'key2': ['one', 'two', 'one'],
                  'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]})
pd.merge(left, right, on=['key1', 'key2'], how='outer')#multiplas colunas

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [8]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print(arr)
np.concatenate([arr, arr], axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [9]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [10]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), 
                index=['a', 'b', 'c'],
                columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), 
                index=['a', 'c'],
                columns=['three', 'four'])
print(df1)
print(df2)
pd.concat([df1, df2], axis=1)

   one  two
a    0    1
b    2    3
c    4    5
   three  four
a      5     6
c      7     8


one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

## TODO Section

### Manipulação de Dados usando Pandas

Usando o dataset Pokemon.csv, faça:

    1) Verifique em qual(is) coluna(s) existem valores faltantes
    2) Preencha os valores faltantes da coluna Type 2 com os valores correspondentes da coluna Type 1
    3) Crie um DataFrame a partir dos dados originais contendo apenas pokemons lendários. Imprima os 5 primeiros
    4) Use apply/applymap para passar todos os valores das colunas Name, Type 1 e Type 2 para minúscula
    5) Agrupe os pokemons por Type 1 e retorne uma Série ordenada pela quantidade em ordem decrescente

In [72]:
import pandas as pd
poke = pd.read_csv('bases/Pokemon.csv')
poke.head(n=10)#10 primeiras linhas

#                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1                  Bulbasaur  Grass  Poison    318  45      49       49   
1  2                    Ivysaur  Grass  Poison    405  60      62       63   
2  3                   Venusaur  Grass  Poison    525  80      82       83   
3  3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4                 Charmander   Fire     NaN    309  39      52       43   
5  5                 Charmeleon   Fire     NaN    405  58      64       58   
6  6                  Charizard   Fire  Flying    534  78      84       78   
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111   
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78   
9  7                   Squirtle  Water     NaN    314  44      48       65   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False  
5       80       65     80           1      False  
6      109       85    100           1      False  
7      130       85    100           1      False  
8      159      115    100           1      False  
9       50       64     43           1      False

In [74]:
# Resposta 1
#print(poke.info)#forma 1
poke.isnull().sum()#forma 2

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
# Resposta 2
import pandas as pd

dfp = pd.DataFrame(poke);
dfp['Type 2'] = dfp['Type 2'].fillna(dfp['Type 1'])
dfp.head()

In [51]:
# Resposta 3
import pandas as pd

dfp = pd.DataFrame(poke);

dfl = dfp[dfp['Legendary'] == True]
dfl.head()

#                 Name    Type 1    Type 2  Total   HP  Attack  \
156  144             Articuno       Ice    Flying    580   90      85   
157  145               Zapdos  Electric    Flying    580   90      90   
158  146              Moltres      Fire    Flying    580   90     100   
162  150               Mewtwo   Psychic   Psychic    680  106     110   
163  150  MewtwoMega Mewtwo X   Psychic  Fighting    780  106     190   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
156      100       95      125     85           1       True  
157       85      125       90    100           1       True  
158       90      125       85     90           1       True  
162       90      154       90    130           1       True  
163      100      154      100    130           1       True

In [47]:
# Resposta 4
import pandas as pd

#poke[['Name', 'Type 1', 'Type 2']] = poke[['Name', 'Type 1', 'Type 2']].applymap(lambda x: x.lower())

dfp = pd.DataFrame(poke);

lower = lambda x: x.lower() if type(x) is str else x
resultLower = dfp.applymap(lower)
resultLower

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              bulbasaur    grass  poison    318  45      49       49   
1      2                ivysaur    grass  poison    405  60      62       63   
2      3               venusaur    grass  poison    525  80      82       83   
3      3  venusaurmega venusaur    grass  poison    625  80     100      123   
4      4             charmander     fire    fire    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                diancie     rock   fairy    600  50     100      150   
796  719    dianciemega diancie     rock   fairy    700  50     160      110   
797  720    hoopahoopa confined  psychic   ghost    600  80     110       60   
798  720     hoopahoopa unbound  psychic    dark    680  80     160       60   
799  721              volcanion     fire   water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [75]:
# Resposta 5
import pandas as pd

poke_ordered = poke.groupby('Type 1').size().sort_values(ascending = False)
print(type(poke_ordered))
poke_ordered

<class 'pandas.core.series.Series'>


Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Dragon       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
dtype: int64